databases:
  - name: lote-a-lote-db
    plan: free
    databaseName: lotealote
    user: lotealote

services:
  - type: web
    name: lote-a-lote
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/listings
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lote-a-lote-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: ADMIN_NAME
        value: Administrador
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
